### ISSUE TITLE
Can't  deploy this maven project

### ISSUE THREAD

**Issue by pospospos2007** [m0ver/bible-online#5]
Hi guys. I tried to build this maven project. 
I build successfully but can't run this project.
And I got this log:
`[INFO] 
[INFO] --- tomcat-maven-plugin:1.1:run (default-cli) @ bible-online ---
[INFO] Skipping non-war project
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.383 s
[INFO] Finished at: 2020-09-06T00:48:43-05:00
[INFO] ------------------------------------------------------------------------
`
Looks like this is not a WAR package, but I still haven't find the jar package in the target. That is weried. Can you provide any clue to me, thx

**Comment by pospospos2007** [comment]
Now  can run using tomcat,but I got this error
`SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Document base /Users/wli004/IdeaProjects/bible-online/src/main/webapp does not exist or is not a readable directory`

**Comment by m0ver** [comment]
Let me provide a full script for you to install it soon.

**Comment by pospospos2007** [comment]
Thank you!
